### ISSUE TITLE
gradle-wrapper JAR missing

### ISSUE THREAD

**Issue by IzzySoft** [richoux/les_sons_en_francais#2]
Could you please add the proper gradle-wrapper JAR next to the `gradle-wrapper.properties` file? Thanks in advance!

**Comment by richoux** [comment]
Thanks for noticing it! Done with ad5a1e688009d5b5ae54c3481c3f7eab97ef808f.

**Comment by IzzySoft** [comment]
Thanks! That worked out excellently :star_struck:

One more question: can you please keep the name of the attached APK consistent (i.e. stay with `app-release.apk`, as you have it now on 1.7) with future releases? Background:

```yaml
  - tag: v1.7
    apks:
      - apk_pattern: app-release\.apk
        apk_url: https://github.com/richoux/les_sons_en_francais/releases/download/v1.7/app-release.apk
        build:
          - sed -r '/signingConfigs.release/d' -i app/build.gradle
          - chmod +x gradlew
          - ./gradlew assembleRelease
```

I need to tell the recipe what to pick :see_no_evil: So whenever it changes, I'd need to check and adjust manually…

More background: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) – and yes, your app succeeded to be part of [Reproducible Builds](https://reproducible-builds.org/) :star_struck:
